version: "2"

linters:
  default: all
  disable:
    - wsl
    - depguard
    - gosec
    - revive
    - unparam
    - varnamelen

  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

formatters:
  enable:
    - gci
    - gofmt
    - golines
